apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: tabula-rasa
spec:
  selector:
    app: tabula-rasa-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: tabula-rasa
spec:
  selector:
    app: tabula-rasa-frontend
  ports:
    - protocol: TCP
      port: 80
