"""empty message

Revision ID: 23d75fd54898
Revises: 6a78304e9969
Create Date: 2023-08-16 13:35:35.497563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23d75fd54898'
down_revision = ''
branch_labels = None
depends_on = None


def upgrade():
       pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass