"""empty message

Revision ID: e2f375df64c1
Revises: cb6f4a48a267
Create Date: 2023-08-10 17:29:07.602049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f375df64c1'
down_revision = 'cb6f4a48a267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('total_tasks', sa.BigInteger(), nullable=True),
    sa.Column('tasks_mapped', sa.BigInteger(), nullable=True),
    sa.Column('tasks_validated', sa.BigInteger(), nullable=True),
    sa.Column('tasks_invalidated', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_deleted_date'), ['deleted_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_deleted_date'))

    op.drop_table('projects')
    # ### end Alembic commands ###
